# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iaH35A5oQPwwmBkdjNgiPogBfkTpyTDp
"""

# Make md5 hash:
  
import hashlib
  
# initializing string
str2hash = input("Your pass")
  
result = hashlib.md5(str2hash.encode())
  
# printing the equivalent hexadecimal value.
print("The hexadecimal equivalent of hash is : ", end ="")
print(result.hexdigest())